# CodingANDCoffeeEQHappy
# Version 1.5.0
# This action downloads weather icons from OpenWeatherMaps website.
name: Download OpenWeatherMap Icons
run-name: ${{ github.actor }} is downloading the required OpenWeatherMap icons.
on: workflow_dispatch
jobs:
  Download-OpenWeatherMap-Icons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Weather icons provided by OpenWeatherMap: https://openweathermap.org/
      # https://openweathermap.org/weather-conditions
      - name: Download Images
        run: |
          echo "Downloading Icons..."
          file_names=("01d@2x.png" "02d@2x.png" "03d@2x.png" "04d@2x.png" "09d@2x.png" "10d@2x.png" "11d@2x.png" "13d@2x.png" "50d@2x.png" "01n@2x.png" "02n@2x.png" "03n@2x.png" "04n@2x.png" "09n@2x.png" "10n@2x.png" "11n@2x.png" "13n@2x.png" "50n@2x.png")

          # Display length of file_names array:
          echo "${#file_names[@]}"

          # Download each file name and save in the repo:
          for file in "${file_names[@]}"; do
            curl -o "./space/assets/images/openweathermap_icons/$file" "https://openweathermap.org/img/wn/$file"
          done

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./space/assets/images/openweathermap_icons/*.png
          git commit -m "🤖 Downloaded OpenWeatherMap icons. 🤖"
          git push https://${{ github.actor }}:$GH_TOKEN@github.com/${{ github.repository }}.git